services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_app_data
      - AUTH_JWT_SECRET=authjwtsecret
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
